### ISSUE TITLE
Default icon color

### ISSUE THREAD

**Issue by ninjaijr** [teknogeek/Stream-Deck-Font-Awesome#1]
just a heads up... .just ran your script without any changes and the icon color was set to #000, so when i ran it... all i got was pure black icons. i manually edited mine to be white icon. :)

**Comment by teknogeek** [comment]
Whoops, good catch! thanks for letting me know, fixed now

**Comment by teknogeek** [comment]
FYI i've also now updated the script to take all the config from CLI params, let me know if you run into any issues :)
